version: '3'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - influxdb-volume:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=hijgi6-wakSyr-tyzxos
      - DOCKER_INFLUXDB_INIT_ORG=wertek
      - DOCKER_INFLUXDB_INIT_BUCKET=solarmonitor
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=VcfbueGtyAD983vMWYrA

  chronograf:
    image: chronograf:1.9
    container_name: chronograf
    depends_on:
      - influxdb
    ports:
      - "8888:8888"
    volumes:
      - chronograf-volume:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=hntXW9N2Q524XeFguhah

volumes:
  influxdb-volume:
  chronograf-volume:
