export class PowerData {
  pa: number;
  pb: number;
  pc: number;
  pt: number;
  epa_c: number;
  epb_c: number;
  epc_c: number;
  ept_c: number;
  epa_g: number;
  epb_g: number;
  epc_g: number;
  ept_g: number;
  iarms: number;
  ibrms: number;
  icrms: number;
  uarms: number;
  ubrms: number;
  ucrms: number;
  freq: number;
  id: number;
  itrms: number;
  pfa: number;
  pfb: number;
  pfc: number;
  pft: number;
  pga: number;
  pgb: number;
  pgc: number;
  qa: number;
  qb: number;
  qc: number;
  qt: number;
  sa: number;
  sb: number;
  sc: number;
  st: number;
  tpsd: number;
  yuaub: number;
  yuauc: number;
  yubuc: number;
  kwhAPer: number;
  kwhBPer: number;
  kwhCPer: number;
  kwhTPer: number;
  kwhAConAcum: number;
  kwhBConAcum: number;
  kwhCConAcum: number;
  kwhTConAcum: number;
  kwhAGerAcum: number;
  kwhBGerAcum: number;
  kwhCGerAcum: number;
  kwhTGerAcum: number;

  constructor(data: any) {
    this.pa = Number(data.pa || 0);
    this.pb = Number(data.pb || 0);
    this.pc = Number(data.pc || 0);
    this.pt = Number(data.pt || 0);
    this.epa_c = Number(data.epa_c || 0);
    this.epb_c = Number(data.epb_c || 0);
    this.epc_c = Number(data.epc_c || 0);
    this.ept_c = Number(data.ept_c || 0);
    this.epa_g = Number(data.epa_g || 0);
    this.epb_g = Number(data.epb_g || 0);
    this.epc_g = Number(data.epc_g || 0);
    this.ept_g = Number(data.ept_g || 0);
    this.iarms = Number(data.iarms || 0);
    this.ibrms = Number(data.ibrms || 0);
    this.icrms = Number(data.icrms || 0);
    this.uarms = Number(data.uarms || 0);
    this.ubrms = Number(data.ubrms || 0);
    this.ucrms = Number(data.ucrms || 0);
    this.freq = Number(data.freq || 0);
    this.id = Number(data.id || 0);
    this.itrms = Number(data.itrms || 0);
    this.pfa = Number(data.pfa || 0);
    this.pfb = Number(data.pfb || 0);
    this.pfc = Number(data.pfc || 0);
    this.pft = Number(data.pft || 0);
    this.pga = Number(data.pga || 0);
    this.pgb = Number(data.pgb || 0);
    this.pgc = Number(data.pgc || 0);
    this.qa = Number(data.qa || 0);
    this.qb = Number(data.qb || 0);
    this.qc = Number(data.qc || 0);
    this.qt = Number(data.qt || 0);
    this.sa = Number(data.sa || 0);
    this.sb = Number(data.sb || 0);
    this.sc = Number(data.sc || 0);
    this.st = Number(data.st || 0);
    this.tpsd = Number(data.tpsd || 0);
    this.yuaub = Number(data.yuaub || 0);
    this.yuauc = Number(data.yuauc || 0);
    this.yubuc = Number(data.yubuc || 0);
  }
}
